version: '3'

services:
  web:
    build: .
    image: my_flask_app:latest
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["flask", "run", "--host=0.0.0.0"]
